### ISSUE TITLE
'make toolchain' fails due to CMake/ninja error

### ISSUE THREAD

**Issue by aaazalea** [dvc94ch/riscv-rust-toolchain#22]
Ubuntu version 16.04 LTS
Linux kernel version 4.13

I'm trying to build this project, but I keep getting errors related to CMake believing my C compiler is incorrect:

```
$ make toolchain
<snip snip>
-- Check for working C compiler using: Ninja
CMake Error:
  The detected version of Ninja () is less than the version of Ninja required
  by CMake (1.3).



CMake Error: Internal CMake error, TryCompile generation of cmake failed
-- Check for working C compiler using: Ninja -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:45 (project)


-- Configuring incomplete, errors occurred!
See also "/home/jakobw/riscv/riscv-rust-toolchain/build/llvm/CMakeFiles/CMakeOutput.log".
See also "/home/jakobw/riscv/riscv-rust-toolchain/build/llvm/CMakeFiles/CMakeError.log".
Makefile:25: recipe for target 'llvm-configure' failed
make: *** [llvm-configure] Error 1

```

As far as I can tell, I do in fact have a sane C compiler - I used it to compile GCC for RISC V just today.

```
$ /usr/bin/cc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 6.3.0-18ubuntu2~16.04' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170519 (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 
```

I'm not familiar with ninja - I previously got the error that I had too old a version of `ninja (0.1.3)` so I installed package `build-ninja` instead of `ninja` and `ninja --version` returns `1.5.1`, but CMake doesn't seem to be able to detect this ninja for some reason.

Any ideas where I might be going wrong?

**Comment by aaazalea** [comment]
Looks like this was caused by accidentally leaving CMake build files in the source directory, which maybe contained this error, which was maybe generated when I ran out of disk space and so the C compiler was unable to compile things and thus unable to appear sane?

Resolved by removing `CMakeCache.txt`, `CMakeFiles/`, `CPackConfig.cmake`, and `CPackSourceConfig.cmake` from `llvm/`

**Comment by tiffanygohnert** [comment]
[main] Configuring project: c_template_qt6 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=C:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/pjt/toolchainfile_windows.cmake -DCMAKE_INSTALL_PREFIX=C:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/result -SC:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/c_template_qt6 -BC:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/build -G "Unix Makefiles"
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:152 (message):
[cmake]   Could not find toolchain file:
[cmake]   C:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/pjt/toolchainfile_windows.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:5 (project)
[cmake] 
[cmake] 
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
[cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=C:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/pjt/toolchainfile_windows.cmake -DCMAKE_INSTALL_PREFIX=C:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/result -SC:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/c_template_qt6 -BC:/Users/Tiffany.Gohnert/Downloads/c_template_qt6/build -G "Unix Makefiles" exited with code: 1
[ctest] Folder is not found in Test Explorer: c:/users/tiffany.gohnert/downloads/c_template_qt6/c_template_qt6
