### ISSUE TITLE
What still needs to be done before upstreaming?

### ISSUE THREAD

**Issue by ids1024** [dvc94ch/riscv-rust-toolchain#24]
Upstream Rust is currently using LLVM 6 (https://github.com/rust-lang/rust/pull/48782). This fork seems to have some additional commits (https://github.com/rust-lang/llvm/compare/6ceaaa4...riscv-rust:rust-llvm-release-6-0-0-riscv). I guess upstreaming RISC-V support in Rust shouldn't be done until the non-Rust specific changes are in upstream LLVM?

It looks like [rust-lang/lld](https://github.com/rust-lang/lld) doesn't have RISC-V support, so I suppose that is needed.

I see there's currently an issue with std on RISC-V (https://github.com/riscv-rust/rust/issues/2), but that probably shouldn't block upstreaming if libcore is working, since it is still useful for bare metal targets.

Anything else?

**Comment by dvc94ch** [comment]
We don't need lld support to upstream. I am mainly waiting on the llvm backend used by rust to have enough riscv support to compile core. Then there are a bunch of issues for it to be useful. Debug info is corrupted [0] and for some reason weirdness occurs when lto=false [0]. Atomic support in llvm is missing which is useful for bare metal too and porting std is mainly on my todo list to be able to run the rustc testsuite to help debug issues like the two mentioned above. This also requires support for atomics.

[0] https://github.com/riscv-rust/riscv-crates/issues/1

**Comment by dvc94ch** [comment]
llvm is ready, work on upstreaming is underway
