### ISSUE TITLE
Rust submodule fetch failed 

### ISSUE THREAD

**Issue by gordonhjs** [dvc94ch/riscv-rust-toolchain#25]
Hi,

I just cloned the repo, it failed to fetch the rust submodule:

`~ git submodule update
error: no such remote ref 842ce79133db9632aaf9f7b4720e9bcb88e3914a
Fetched in submodule path 'rust', but it did not contain 842ce79133db9632aaf9f7b4720e9bcb88e3914a. Direct fetching of that commit failed.
`

**Comment by dvc94ch** [comment]
fixed
