### ISSUE TITLE
"OBSOLETE" link broken

### ISSUE THREAD

**Issue by laanwj** [dvc94ch/riscv-rust-toolchain#28]
This repository is marked as obsolete, and the following is mentioned as replacement:

> This is no longer the recommended way to get a Rust toolchain for RISCV. Instead, you can clone the riscv-rust/rust fork of Rust and build it as normal:

However, there is no `riscv-rust/rust` repository on github either. Did it move again?

**Comment by dvc94ch** [comment]
you can use rustup add riscv32imac-unknown-none-elf

**Comment by laanwj** [comment]
thanks!
