### ISSUE TITLE
RV64 support?

### ISSUE THREAD

**Issue by sunnystormy** [dvc94ch/riscv-rust-toolchain#5]
I'm interested in testing the 64-bit capabilities of RISC-V with Rust, and I noticed you have a JSON file for RV32. I wanted to know if it would be easy to add 64-bit support by creating a RV64 JSON as well?

**Comment by dvc94ch** [comment]
There is currently RV64IMFD support in the LLVM backend.

**Comment by sunnystormy** [comment]
Awesome! Looking forward to using it. Thank you very much! 😺

**Comment by sunnystormy** [comment]
Is there currently any RV64 **Atomic** support in the backend? Just curious.

**Comment by devurandom** [comment]
According to @dvc94ch, A and C codegen (in LLVM) is currently being worked on.

**Comment by dvc94ch** [comment]
Tracked in https://github.com/riscv-rust/rust/issues/2
